name: Setup Shank CLI
description: 'Setup Shank CLI'

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v2
      name: Cache Shank CLI
      id: cache-shank-cli
      with:
        path: |
          ~/.cargo/bin/shank
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target/
        key: shank-cli-${{ runner.os }}-v0000-${{ env.SHANK_VERSION }}
    - run:
        cargo install shank-cli
      shell: bash
      if: steps.cache-shank-cli.outputs.cache-hit != 'true'
