name: Version updates

on:
  pull_request_review:
    types: [submitted, edited]

permissions:
  id-token: write
  contents: write
  packages: write
  issues: write # make comment
  pull-requests: write # open PR

env:
  NODE_VERSION: 17.0.1
  # todo: pull from package's Cargo.toml?
  ANCHOR_VERSION: 0.22.0
  RUST_TOOLCHAIN: stable

jobs:
  dump-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  qualify-workflow-run:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.qualify-run.outputs.value }}
    steps:
      - uses: actions/checkout@v3
      - id: qualify-run
        shell: bash
        run: |
          WORKFLOW_QUALIFIER=${{ contains(fromJson('["OWNER", "MEMBER", "CONTRIBUTOR"]'), github.event.review.author_association) == true }}
          WORKFLOW_QUALIFIER=$WORKFLOW_QUALIFIER && ${{ contains(fromJson('["approved", "commented"]'), github.event.review.state) == true }}
          WORKFLOW_QUALIFIER=$WORKFLOW_QUALIFIER && ${{ github.event.pull_request.number > 0 }}
          echo "::set-output name=value::$WORKFLOW_QUALIFIER"

  get-changes-scope:
    needs: [qualify-workflow-run]
    if: ${{ needs.qualify-workflow-run.outputs.output == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      changed-packages: ${{ steps.get-changed-package-scope.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - name: List changed files
        uses: ./.github/actions/list-changed-files
        id: list-changed-files
        with:
          pull-number: ${{ github.event.pull_request.number }}
          exclude: '[".github", "Cargo.lock", "Cargo.toml", "js/idl", "packge.json", "yarn.lock"]'

      # map fetched changed files to package / lang (list)
      - name: Get scope of changed packages
        uses: actions/github-script@v4
        id: get-changed-package-scope
        with:
          # update regexp to consider other subdirs - e.g. `rust|test|cli|<etc>`
          script: |
            const files = ${{ steps.list-changed-files.outputs.changed-files }}
            const regexp = /[a-zA-Z\-]+\/(js|program)/g
            const uniqueFilesObj = files.reduce((p, file) => {
              const match = file.match(regexp)
              if (match) {
                // use first match result
                if (!p[match[0]]) p[match[0]] = 1
              }
              return p
            }, {})
            return JSON.stringify(Array.from(Object.keys(uniqueFilesObj)).map((el) => `\"${el}\"`))

  get-version-scope:
    needs: [qualify-workflow-run]
    if: ${{ needs.qualify-workflow-run.outputs.output == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      versioning: ${{ steps.parse-version-info.outputs.versioning }}
      has-versioning: ${{ steps.parse-version-info.outputs.has-versioning }}
    steps:
      - uses: actions/checkout@v3

      # GH doesn't process or format body fields, so we do some light processing so that multiline comments will break inputs
      - name: Process content body
        id: process-content-body
        run: |
          REVIEW_CONTENT=$(cat << EOF
          ${{ github.event.review.body }}
          EOF
          )
          REVIEW_CONTENT="${REVIEW_CONTENT//\'/}"
          REVIEW_CONTENT="${REVIEW_CONTENT//$'\n'/\\n}"
          REVIEW_CONTENT="${REVIEW_CONTENT//$'\r'/\\r}"
          echo "::set-output name=content::$REVIEW_CONTENT"
        shell: bash

      - name: Log processed content body
        run: echo "${{ steps.process-content-body.outputs.content }}"
        shell: bash

      - name: Parse version info from review
        uses: ./.github/actions/parse-version-command
        id: parse-version-info
        with:
          body: ${{ steps.process-content-body.outputs.content }}

  setup-versions:
    needs: [qualify-workflow-run]
    if: ${{ needs.qualify-workflow-run.outputs.output == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get-solana-versions.outputs.value }}
    steps:
      - uses: actions/checkout@v3
      - id: get-solana-versions
        uses: ./.github/actions/get-solana-versions

  update-pr-with-changes:
    needs: [get-changes-scope, get-version-scope, setup-versions]
    if: ${{ needs.get-version-scope.outputs.has-versioning == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SOLANA_VERSION: ${{fromJson(needs.setup-versions.outputs.versions)}}
    env:
      SOLANA_VERSION: ${{ matrix.SOLANA_VERSION }}

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-linux-build-deps
      - uses: ./.github/actions/install-solana
        with:
          solana_version: ${{ env.SOLANA_VERSION }}
      - uses: ./.github/actions/install-rust
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - uses: ./.github/actions/install-anchor/

      - name: Make version changes
        uses: ./.github/actions/make-version-changes
        id: make-version-changes
        with:
          changed-packages: ${{ needs.get-changes-scope.outputs.changed-packages }}
          versioning: ${{ needs.get-version-scope.outputs.versioning }}
          to-branch: ${{ github.event.pull_request.base.ref }}
          to-repository: ${{ github.event.pull_request.base.repo.full_name }}
          from-branch: ${{ github.event.pull_request.head.ref }}
          from-repository: ${{ github.event.pull_request.head.repo.full_name }}
          pull-number: ${{ github.event.pull_request.number }}
